### ISSUE TITLE
Make the CLI more automation-friendly

### ISSUE THREAD

**Issue by detoxhby** [wamdam/backy2#42] opened 2019-12-02 14:56 UTC
I really like the concept of this tool and it does its core functionality very well ... but according to current documentation and help, it is a pain to perform anything that should be scripted.

First and most important feature missing is the ability to list the backups in a simply form to be able to work with it in scripts. This happens for the automated retention policy handling, for ex. to keep 7 daily, 3 weekly, and 1 monthly backup.

As you need the exact hash to be able to `rm` anything, you need to acquire a proper list in order to do it (with proper date ordering), but there is no support for this in the CLI as its output is unusable for scripting purposes.

You may say that I should start scripting against the sqlite database backend, but:
 - it is dangerous as the internal structure may change any time in the future
 - not convenient for easy tasks
 - every other backup tool has these abilities as backups are **NOT** created and deleted by humans

I may miss something or there are other frontends to use for this, but I wasn't able to find information about it. Please give me hints if that is the case.

Thank you

**Comment by wamdam** [comment] 2019-12-09 20:16
Try -m.
Example: backy -m ls|cut -d'|' -f 7

**Comment by 3001io** [comment] 2019-12-20 02:10
Using backy2 -m you get machine readable "|" delimited lines.
For example, the following will give the last backy2 backup for the vm in $vm
backy2 ls -m $vm | tail -n 1 | awk -F '|' '{ print $7 }'
or grep the output by tag or whatever

**Comment by 3001io** [comment] 2019-12-20 02:11
Regarding sqlite. DON'T USE THAT! Use postgres. There is a known issue with deleting backups and I fell in that trap, too.

**Comment by detoxhby** [comment] 2019-12-22 10:42
Thanks for hints guys.

As I got the answer how to do this basic task, but I still find it pretty cumbersome compared to other backup solutions. I suggets on improving these supplementary functionalities for wider adaption.

**Comment by wamdam** [comment] 2019-12-23 21:29
So you may of course tell us ignorants how a perfect output could look like instead of just ranting?

**Comment by detoxhby** [comment] 2019-12-24 11:08
I had no intentions of ranting, tried to be suggestive. I say pardon if I was deceptive.

What I was trying to say is that the tooling usability improvements should receive care over the base functionality (which is super nice already; only compression would be beneficial). To be able to do simple administrative tasks programmatically, without the need to parse and (re-)process the output, thus be less error prone to deal with in production system.

To pick one part, these are good examples with rich feature set that cover most use cases of retention:
 - https://borgbackup.readthedocs.io/en/stable/usage/prune.html - note on the date (`keep-X`) and count (`keep-last`) based conventions, and customization support (`keep-within`), no extra scripting necessary for either way
 - http://duplicity.nongnu.org/vers8/duplicity.1.html - note on `remove-X`; easy to handle basic retention policy without messing with specific versions by hand

I'm willing to provide more use cases and scenarios if you may need information.

**Comment by wamdam** [comment] 2019-12-27 14:21
Thanks, will have a look.

**Comment by wamdam** [comment] 2019-12-30 21:14
Alright, let's discuss this further.
I've just added a few quirks that should make automation easier - at least it does this on my installation.

1. Improving machine output. You may now pass "-s" in addition to "-m" to skip the header. This means, you may now leave " | tail -n+2" from the output chain.
2. Improving `ls` output. You may now add a fields list via `-f`. Example usage: `backy2 -ms ls -f uid` in order to only output the uid.
3. Added `expire` feature. You can now (in addition to tags and automatic b_ tags) add an expiration date for the version like with `backy2 backup -e 2020-01-14 file:///something test`. This shows in `ls` in the column `expire` and all expired backups (expire < today) can be listed with the `-e` switch on ls. So for selection of all expired versions you may now just use `backy2 -ms ls -f uid -e`. http://backy2.com/docs/cleanup.html#using-the-expire-feature has a complete example.

What do you think?

**Comment by wamdam** [comment] 2019-12-30 21:17
ah and @3001io - the sqlite issue is gone by today.

**Comment by wamdam** [comment] 2019-12-31 10:41
With the latest feature additions, scripting a backup including SLA checks is now very simple. Please have a look at
https://github.com/wamdam/backy2/tree/master/demo
and tell me what you think. The scripts would actually be all you need. Plus a monitoring solution maybe.

**Comment by detoxhby** [comment] 2020-01-01 14:36
> Alright, let's discuss this further.
> I've just added a few quirks that should make automation easier - at least it does this on my installation.
> 
> 1. Improving machine output. You may now pass "-s" in addition to "-m" to skip the header. This means, you may now leave ` | tail -n+2` from the output chain.

Sounds nice, but the flag's char may be a bit misleading and ambiguous with the `backup` command's `-s`. I would recommended allowing only the long option name (like `--simple` or `--no-header` or `--exclude-headers`)
> 2. Improving `ls` output. You may now add a fields list via `-f`. Example usage: `backy2 -ms ls -f uid` in order to only output the uid.

Awesome! This will give enough freedom to achive specific solutions.
> 3. Added `expire` feature. You can now (in addition to tags and automatic b_ tags) add an expiration date for the version like with `backy2 backup -e 2020-01-14 file:///something test`. This shows in `ls` in the column `expire` and all expired backups (expire < today) can be listed with the `-e` switch on ls. So for selection of all expired versions you may now just use `backy2 -ms ls -f uid -e`. http://backy2.com/docs/cleanup.html#using-the-expire-feature has a complete example.

The problem with this approach is that it is immutable and cannot be changed/corrected after the backup has been created. For example, I create a backup with 60 days expiration but then some department realize the data contains sensitive user information: to comply with GDPR, I have to purge backup data after 30 days which is unachivable as I cannot mark the existing backup to be deleted earlier (note: I cannot and don't want to delete at that date I got the information about the data leak, would happen only ~2 weeks later which I would easily forget as a human and problem arise)

I recommend following the borg way of handling the expiration: let the `expire` command define what should be purged (for convenient daily, weekly, monthly; and count-wise).
> 
> What do you think?

👍 You did a nice job overall towards the goal to make the tool easier to use and less error prone.

-----

> With the latest feature additions, scripting a backup including SLA checks is now very simple. Please have a look at
> https://github.com/wamdam/backy2/tree/master/demo
> and tell me what you think. The scripts would actually be all you need. Plus a monitoring solution maybe.

The SLA term seems a bit misleading for end users. I know why you chose this but "_maximum age of backups_" would fit better on the purpose it serves.

-----

I'm gonna try to refactor the backup scripts in the next weeks and report back if something may be missing or problematic to handle.

**Comment by wamdam** [comment] 2020-01-03 12:25
> > 1. Improving machine output. You may now pass "-s" in addition to "-m" to skip the header. This means, you may now leave ` | tail -n+2` from the output chain.

> Sounds nice, but the flag's char may be a bit misleading and ambiguous with the `backup` command's `-s`. I would recommended allowing only the long option name (like `--simple` or `--no-header` or `--exclude-headers`)

Not really. There are backy2 arguments and command arguments. Those for backy2 must follow the backy2 call (backy2 -ms <command>) and the command arguments must follow the command.

> > 1. Improving `ls` output. You may now add a fields list via `-f`. Example usage: `backy2 -ms ls -f uid` in order to only output the uid.
> Awesome! This will give enough freedom to achive specific solutions.

In addition, the latest master has a backy2 '-r' argument to output human readable sizes.

> > 1. Added `expire` feature. You can now (in addition to tags and automatic b_ tags) add an expiration date for the version like with `backy2 backup -e 2020-01-14 file:///something test`. This shows in `ls` in the column `expire` and all expired backups (expire < today) can be listed with the `-e` switch on ls. So for selection of all expired versions you may now just use `backy2 -ms ls -f uid -e`. http://backy2.com/docs/cleanup.html#using-the-expire-feature has a complete example.
> 
> The problem with this approach is that it is immutable and cannot be changed/corrected after the backup has been created. For example, I create a backup with 60 days expiration but then some department realize the data contains sensitive user information: to comply with GDPR, I have to purge backup data after 30 days which is unachivable as I cannot mark the existing backup to be deleted earlier (note: I cannot and don't want to delete at that date I got the information about the data leak, would happen only ~2 weeks later which I would easily forget as a human and problem arise)

It is not immutable, you can even change or remove it via the "expire" command. It does not even cause any deletions. You must still delete with `backy rm`. With the new `ls` filter (`-e`) it allows you to
`for uid in $(backy2 -ms ls -f uid); do backy2 rm "$uid"; done`.

**Comment by 3001io** [comment] 2020-01-03 16:27
I'm very interested to incorporate this in my automation tools. There are two more features I think would be helpful. 
1. Similar to backy2 ls, it would be helpful to add a backy2 mv to rename backups.
2. It would be very helpful to save the ceph RBD snapshot name with the backup in addition to a "common" name.

**Comment by 3001io** [comment] 2020-01-03 16:36
> 
> 
> ah and @3001io - the sqlite issue is gone by today.

Thanks, I was able to successfully migrate to postgresql by 
1) Creating the user and database, 
2) Exporting all version metadata with sqlite, 
3) Switching to postgresql in the backy2 config and then importing the versions.

**Comment by wamdam** [comment] 2020-01-03 17:14
>     1. Similar to backy2 ls, it would be helpful to add a backy2 mv to rename backups. This would likely be most valuable to new users, or to people who find the naming convention they chose doesn't accommodate edge cases.

Might be an addition. For now, you can do this in sql - probably without side effects.

>     2. It would be very helpful to save the ceph RBD snapshot name with the backup in addition to a "common" name.

That's already possible. See the `-s` option for backup: backy2.com/docs/backup.html
We use this exactly for that purpose.

**Comment by 3001io** [comment] 2020-01-03 18:00
I understand the -s option, what I mean is, that allows you to add a "friendly" snapshot name (the example is "backup1" and "backup2") which may be different than the name used by the rbd snap process.

**Comment by detoxhby** [comment] 2020-01-03 19:39
> Not really. There are backy2 arguments and command arguments. Those for backy2 must follow the backy2 call (backy2 -ms ) and the command arguments must follow the command.

I agree, but I met lot of so-called "sysadmins" during the years who were not able to realize that option position indeed _does matter_ on calling commands. I'm not going to argue about "_dumb people shouldn't use these kind of stuff_", I just made a justification. I'm on your side of this topic.

> It is not immutable, you can even change or remove it via the "expire" command.

I was blind probably, but couldn't find the related documentation on the site at the time I answered, but I've read that now, all good, thanks! ✅

**Comment by 3001io** [comment] 2020-01-03 20:01
I truly appreciate your responsiveness here. We are VERY pleased with Backy2 overall even though (luckily) we haven't actually needed to restore anything in anger.

**Comment by wamdam** [comment] 2020-01-04 14:45
> > It is not immutable, you can even change or remove it via the "expire" command.
> I was blind probably, but couldn't find the related documentation on the site at the time I answered, but I've read that now, all good, thanks!

Yes, I try to keep the docs up with the features - however I often miss one or two perfect spots of the docs. If you find something missing, please open a ticket.

**Comment by wamdam** [comment] 2020-01-04 15:05
> I understand the -s option, what I mean is, that allows you to add a "friendly" snapshot name (the example is "backup1" and "backup2") which may be different than the name used by the rbd snap process.
> The reason why this might be helpful, for example, in Proxmox, snaps have a certain naming convention and are displayed in a tree, Reverting to a snap is easy, but you then want to delete any backup that came after that snap.

Hmm - what bothers me about the idea is that that would be a third "name" for a version. We already have 2. When the snapshot column didn't exist, we internally just used the ceph notation (backup name@snapshot name) and spit it when needed in integration scripts.
Then the idea of better integration and (in some way) schedulers, expiration and sla came up and that required to have always the same name for the same backup. This led to really split the snapshot name or to implement an implicit splitting in backy2. As explicit is better than implicit, I added the snapshot name feature.
This was a requirement for backy2 features, not a convenience addition.
However, as backy does not require a third name for anything, I would prefer that you define whatever splitting you need for your usecase. I'm trying very hard to keep backy2 small and simple. That's why the new scheduler and expiration stuff are only helpers for integration and not full blown solutions.

backy2's design goal is to keep it simple and to do only one thing and that thing well. Just like the unix philosophy. That is the reason why I need hard integration requirements or at least significant integration simplifications in order to add new features. So if it's impossible or unnecessary hard for you to use what's here, just argue.

**Comment by 3001io** [comment] 2020-01-06 14:52
Ok. I understand. The problem is if I add a snapshot name ("snapshot name") in backy2 that is different than the snapshot name ("volume"@"snapshotname") in Ceph then I am referring to the same source snapshot with two different names. Is there going to be a problem if I use the Ceph snapshot name (volume@snapshotname) as the name I use for the snapshot in backy2?
For example, my scripting creates a Proxmox snapshot on the Ceph RBD named vm-100-disk-0@snap_12_12_18_06_08_17 where (12_12_18_06_08_17) is (date %Y_%m_%d_%h_%m_%s).

**Comment by wamdam** [comment] 2020-01-06 16:54
For backy2 the snapshot name is just that - a name. It has nothing to do with anything else. For your automation you can allways split the name by "@". Example::

  SNAP=$(echo "snap@date" | awk -F'@' '{ print $1 }')
  DATE=$(echo "snap@date" | awk -F'@' '{ print $2 }')

So you can put anything you like in there.

**Comment by wamdam** [comment] 2020-01-27 08:42
As there was no comment within 14 days, I'm closing this ticket now.

**Closed by wamdam** 2020-01-27 08:42 UTC
